ALTER TABLE "GSTInvoice"
  ADD COLUMN "customerName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "customerEmail" TEXT,
  ADD COLUMN "customerMobileNumber" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "customerBusinessName" TEXT,
  ADD COLUMN "placeOfSupply" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "sourceState" TEXT,
  ADD COLUMN "destinationState" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "taxType" TEXT NOT NULL DEFAULT 'CGST_SGST',
  ADD COLUMN "cgstTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "sgstTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "igstTotal" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "html" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "pdfStatus" TEXT NOT NULL DEFAULT 'NOT_GENERATED';

ALTER TABLE "InvoiceItem"
  ADD COLUMN "sku" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "taxableValue" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "cgstRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN "cgstAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "sgstRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN "sgstAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "igstRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN "igstAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
