import Handlebars from "handlebars";

const { escapeExpression } = Handlebars;

export function gallery(entries) {
  const payload = JSON.stringify(entries).replaceAll("<", "\\u003c");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Customer email templates | Surgical Medical Equipment</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f3faf9;color:#123f3c}header{padding:24px 28px;background:#fff;border-bottom:1px solid #c4e4e0}h1{font-size:24px;margin:6px 0 10px}p{line-height:1.6;margin:0}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:#0f6f68;font-weight:bold}.layout{display:grid;grid-template-columns:270px minmax(0,1fr);min-height:80vh}nav{background:#fff;border-right:1px solid #c4e4e0;padding:16px}button,select,a{font:inherit}nav button{display:block;text-align:left;width:100%;padding:12px;border:0;border-radius:5px;background:transparent;color:#123f3c;cursor:pointer;line-height:1.4}nav button[aria-pressed=true]{background:#e5f5f3;color:#0f6f68;font-weight:bold}button:focus-visible,a:focus-visible,select:focus-visible{outline:3px solid #17a89d;outline-offset:3px}main{padding:24px;min-width:0}.toolbar{display:flex;gap:16px;align-items:end;flex-wrap:wrap;margin:18px 0}label{display:grid;gap:6px;font-size:13px;font-weight:bold}select{background:#fff;color:#123f3c;padding:10px;border:1px solid #93bab5;border-radius:4px;max-width:100%}.subject{font-size:18px;font-weight:bold;line-height:1.5;overflow-wrap:anywhere}.trigger{font-size:14px;color:#55716e;max-width:850px}.stage{overflow:auto;padding:12px 0;min-height:400px}iframe{display:block;border:0;margin:auto;width:100%;max-width:680px;min-height:760px}.downloads{display:flex;gap:16px;flex-wrap:wrap;margin:16px 0}a{color:#0f6f68;text-underline-offset:3px;font-size:14px}details{margin:18px 0;max-width:850px}summary{cursor:pointer;font-size:14px;font-weight:bold}pre{background:#fff;border:1px solid #c4e4e0;padding:16px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px;line-height:1.6}.status{font-size:12px;color:#55716e;margin-top:10px}@media(max-width:760px){header{padding:20px}.layout{grid-template-columns:1fr}nav{display:flex;overflow-x:auto;padding:8px;border-right:0;border-bottom:1px solid #c4e4e0}nav button{flex:0 0 170px}main{padding:16px}iframe{max-width:100%}.toolbar{gap:10px}}
</style></head><body><header><div class="eyebrow">Surgical Medical Equipment</div><h1>Customer email templates</h1><p>12 simple transactional emails. Preview each status in light or dark mode.</p><p class="status">Local drafts · Fictional sample data · Not uploaded to MSG91 · No messages sent</p></header><div class="layout"><nav aria-label="Customer templates">${entries.map((entry, index) => `<button type="button" data-index="${index}" aria-pressed="${index === 0}">${String(index + 1).padStart(2, "0")} &nbsp; ${escapeExpression(entry.name)}</button>`).join("")}</nav><main><div class="subject" id="subject" aria-live="polite"></div><p class="trigger" id="trigger"></p><div class="toolbar"><label>Scenario<select id="scenario"></select></label><label>Colour mode<select id="theme"><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Preview width<select id="width"><option value="680">Desktop</option><option value="360">Mobile · 360px</option><option value="320">Small mobile · 320px</option></select></label></div><div class="downloads"><a id="html-download" download>Download MSG91 HTML</a><a id="text-download" download>Download plain text</a><a id="sample-download" download>Download sample data</a><a href="../msg91-create-templates.json" download>Download all creation payloads</a></div><div class="stage"><iframe id="email" title="Customer email preview" sandbox="allow-same-origin"></iframe></div><details><summary>Sample variables</summary><pre id="variables"></pre></details><details><summary>Plain-text preview</summary><pre id="plain"></pre></details></main></div><script type="application/json" id="template-data">${payload}</script><script>
const entries=JSON.parse(document.getElementById('template-data').textContent);let selected=0;const frame=document.getElementById('email');const scenario=document.getElementById('scenario');const theme=document.getElementById('theme');const width=document.getElementById('width');
function render(){const entry=entries[selected];const current=entry.scenarios[Number(scenario.value)||0];document.getElementById('subject').textContent=current.subject;document.getElementById('trigger').textContent=entry.trigger;frame.style.width=width.value+'px';frame.style.height='760px';frame.srcdoc=current[theme.value];document.getElementById('variables').textContent=JSON.stringify(current.variables,null,2);document.getElementById('plain').textContent=current.text;document.getElementById('html-download').href='../html/'+entry.slug+'.html';document.getElementById('text-download').href='../text/'+entry.slug+'.txt';document.getElementById('sample-download').href='../samples/'+entry.slug+'.json';}
function select(index){selected=index;document.querySelectorAll('nav button').forEach((button,i)=>button.setAttribute('aria-pressed',String(i===index)));scenario.replaceChildren(...entries[index].scenarios.map((item,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=item.name;return option;}));render();}
document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',()=>select(Number(button.dataset.index))));scenario.addEventListener('change',render);theme.addEventListener('change',render);width.addEventListener('change',render);frame.addEventListener('load',()=>{const doc=frame.contentDocument;frame.style.height=Math.max(420,doc.documentElement.scrollHeight)+'px';doc.addEventListener('click',event=>{if(event.target.closest('a'))event.preventDefault();});});select(0);
</script></body></html>\n`;
}
